---
- name: 'Instala pacotes do sistema operacional'
  apt:
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: 'Cria banco de dados MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Cria usuário do MySQL'
  no_log: yes
  mysql_user: 
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "{{ wp_host_ip }}"
    state: present
  become: yes

- name: 'Garante que meu ip possa acessar o banco'
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: "bind-address"
    value: "0.0.0.0"
  register: my_cnf
  become: yes
  notify:
    - restart mysql