Vagrant.configure("2") do |config|
    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.box = "ubuntu/trusty64"
        wordpress.vm.network "public_network", ip: '192.168.0.121', bridge: "Realtek PCIe GbE Family Controller"

        wordpress.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
            vb.name = 'Ansible Wordpress'
        end

        wordpress.vm.provision "shell",
            inline: "cat /vagrant/keys/id_ansible.pub >> .ssh/authorized_keys"
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "ubuntu/bionic64"
        ansible.vm.network "public_network", ip: '192.168.0.120', bridge: "Realtek PCIe GbE Family Controller"

        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
            vb.name = 'Ansible Controle'
        end

        ansible.vm.provision "shell",
            inline: "cp /vagrant/keys/id_ansible  /home/vagrant && \
                    chmod 600 /home/vagrant/id_ansible"

        ansible.vm.provision "shell", 
            inline: "apt-get update && \
                    apt-get install -y software-properties-common && \
                    apt-add-repository --yes --update ppa:ansible/ansible && \
                    apt-get install -y ansible"

        ansible.vm.synced_folder "./shared", "/shared"
    end
end